name: aromatizacion_app
description: Aplicación de aromatización profesional

publish_to: "none" # No publicar en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  timezone: ^0.9.0

  
  intl: ^0.18.1

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
